    hashview:
        build: .
        container_name: hashview
        dockerfile: hashview.docker
        links:
            - mysqldb
        ports:
            - "4567"
        restart: always
        depends_on:
            - php
            - mysqldb

    mysqldb:
        image: mysql
        container_name: mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
