version: '3'
 
services:
  mysql:
    image: mysql
    container_name: mysql-hashview
    environment:
      MYSQL_ROOT_PASSWORD: "hashview"
      MYSQL_DATABASE: "hashview"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - hashview_mysql_net
 
  hashview:
    depends_on:
      - mysql
    build: .
     context: .
     dockerfile: hashview.docker
    container_name: hashview
    ports:
      - 4567:4567
    links:
      - mysql:mysql
    restart: always
    networks:
      - hashview_mysql_net
 
volumes:
  mysql_data:
 
networks:
  hashview_mysql_net:
    driver: bridge
