version: "3"

services:
   mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=hashview
      - MYSQL_USER=hashview
      - MYSQL_PASSWORD=hashview
      - MYSQL_DATABASE=hashview
    restart: always
   hashview:
    build: .
    container_name: hashview
    dockerfile: hashview.docker
    links:
      - mysql:mysql
    ports:
      - "4567"
    depends_on:
      - mysql
    restart: always
networks:
  default:
    external:
      name: docker_default
