   mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=hashview
      - MYSQL_USER=hashview
      - MYSQL_PASSWORD=hashview
      - MYSQL_DATABASE=hashview
    ports:
      - "3306:3306"
    restart: always
   hashview:
    build: .
    container_name: hashview
    dockerfile: hashview.docker
    links:
      - mysql:mysql
    ports:
      - "4567:4567"
    restart: always
