    mysqldb:
        image: mysqldb
        container_name: mysqldb
        restart: always
        hostname: mysqldb
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        
        expose:
            - "3306"
        ports:
            - "3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"


    hashview:
        build: .
        container_name: hashview
        dockerfile: hashview.docker
        links:
            - mysqldb
        ports:
            - "4567"
        restart: always
